services:

  app1:
    container_name: app1
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - MESSAGE=${MESSAGE}

  app2:
    container_name: app2
    build: ./api
    ports:
      - "3001:3000"
    environment:
      - MESSAGE=${MESSAGE}

  app3:
    container_name: app3
    build: ./api
    ports:
      - "3002:3000"
    environment:
      - MESSAGE=${MESSAGE}

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - lab02_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  lab02_data: